########################################################
###REDIS (RedisProperties) redis基本配置
########################################################
# database name
spring:
  redis:
    database: 0
    host: 47.99.243.252
    password: 123456
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
# server host1 单机使用，对应服务器ip
#spring.redis.host=127.0.0.1
# server password 密码，如果没有设置可不配
#spring.redis.password=
#connection port  单机使用，对应端口号
#spring.redis.port=6379
# pool settings ...池配置
#    pool:
#      max-idle: 8
#      min-idle: 0
#      max-active: 8
#      max-wait: 1
# name of Redis server  哨兵监听的Redis server的名称
#    sentinel:
#      master: mymaster
# comma-separated list of host:port pairs  哨兵的配置列表
#      nodes: 192.168.13.57:26379,192.168.13.58:26379,192.168.13.54:26379